[workspace]
resolver = "2"
members = [
    "contracts/factory",
    "contracts/oracle",
    "contracts/pair",
#    "contracts/pair_anchor",
    "contracts/pair_stable",
    "contracts/router",
    "contracts/token",
    "contracts/tokenomics/maker",
#    "contracts/tokenomics/staking",
#    "contracts/tokenomics/vesting",
#    "contracts/tokenomics/xastro_token",
    "contracts/whitelist",
    "packages/*",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
