[package]
name = "astroport"
version = "2.0.0"
authors = ["Astroport"]
edition = "2021"
description = "Common Astroport types, queriers and other utils"
license = "Apache-2.0"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std.workspace = true
cw-storage-plus.workspace = true
cw20.workspace = true
schemars.workspace = true
serde.workspace = true
uint.workspace = true

[dev-dependencies]
cosmwasm-schema.workspace = true
