[package]
name = "token-bridge-terra"
version = "0.1.0"
authors = ["Yuriy Savchenko <yuriy.savchenko@gmail.com>"]
edition = "2018"
description = "Wormhole token bridge"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
astroport = { path = "../../packages/astroport", default-features = false }
cosmwasm-std = "1.0.0"
cosmwasm-storage = "1.0.0"
cw20 = "0.13.4"
cw20-base = { version = "0.13.4", features = ["library"] }
cw20-wrapped = { path = "../cw20-wrapped", features = ["library"] }
generic-array = { version = "0.14.5" }
hex = "0.4.3"
paloma-cosmwasm = { path = "../../packages/paloma_cosmwasm" }
schemars = "0.8.10"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
sha3 = { version = "0.10.1", default-features = false }
thiserror = { version = "1.0.31" }
wormhole-bridge-terra = { path = "../wormhole", features = ["library"] }

[dev-dependencies]
serde_json = "1.0"
