[package]
name = "astroport-vesting"
version = "1.0.0"
authors = ["Astroport"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
astroport = { path = "../../../packages/astroport", default-features = false }
cosmwasm-std = "1.0.0"
cw-storage-plus = { version = "0.13.2", features = ['iterator'] }
cw2 = "0.13.2"
cw20 = "0.13.2"
paloma-cosmwasm = { path = "../../../packages/paloma_cosmwasm" }
schemars = "0.8.10"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = "1.0.31"

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0", default-features = false }
astroport-token = {path = "../../token"}
