name: Test

on: [pull_request]

jobs:
  rust-lint-and-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        manifest:
          - sdk/rust/Cargo.toml
    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Install stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
          default: true

      - run: cargo fetch --verbose --locked
      - run: cargo check --verbose --workspace --locked --all-targets
      - run: cargo test --verbose --workspace --locked
#      - run: cargo clippy --all --all-targets -- -D warnings
      - run: cargo fmt --all -- --check
