name: Tests and Checks

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-lint-and-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        manifest:
          - sdk/rust/Cargo.toml
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out source
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git/checkouts
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
          default: true

      - run: cargo fetch --verbose --locked
      - run: cargo check --verbose --workspace --locked --all-targets
      - run: cargo test --verbose --workspace --locked --no-fail-fast
      - run: cargo clippy --all --all-targets -- -D warnings
      - run: cargo fmt --all -- --check
      - run: ./bin/generate_schemas.sh
      - name: Schema Changes
        run: git diff --exit-code
